###############################################################################
# Prelude
###############################################################################

# Set TREESITTER_INCDIR/TREESITTER_LIBDIR for dune; generated by configure.
# '-include' so that the first build before configure still works.
# coupling: codemap/Makefile, codegraph/Makefile, osemgrep/Makefile
-include tree-sitter-config.mk

###############################################################################
# Main targets
###############################################################################

default:
	bash -c "dune build _build/install/default/bin/{syncweb,lpizer,test.bc}"

syncweb-only:
	dune build _build/install/default/bin/syncweb

all:
	dune build
clean:
	dune clean
install:
	dune install syncweb
	dune install lpizer

#TODO: use testo, run syncweb on demos/ ? or in tests/syncweb/?
#TODO: ./bin/lpizer -verbose -lang c tests/lpizer/*.c
test:
	./bin/lpizer -verbose -lang ocaml tests/lpizer/*.ml
	./test

setup:
	opam install --deps-only ./syncweb.opam ./lpizer.opam -y

.PHONY: all clean install test

build-docker:
	docker build -t "syncweb" .

###############################################################################
# Developer targets
###############################################################################

# See https://github.com/aryx/codemap and https://github.com/aryx/fork-efuns
visual:
	codemap -screen_size 3 -filter semgrep -efuns_client efuns_client -emacs_client /dev/null .

index:
	$(MAKE) clean
	$(MAKE)
	codegraph_build -lang cmt .

syncweb.opam lpizer.opam: dune-project
	dune build $@
