##############################################################################
# Noweb illustration
##############################################################################
simple.pdf: simple.orig
	noweave -index -latex simple.orig > simple.tex
	pdflatex simple.tex

