#!/bin/bash

#update: can also do that:
#noweave -filter "sed '/^@use /s/_/\\_/g;/^@defn /s/_/\\_/g'

# must use \include not \input in nw file to make scopehack work

#noweave -n -delay -index -latex -filter scopehack $*

#-filter "sed '/^@use /s/_/\\_/g;/^@defn /s/_/\\_/g'" $*

