#!/usr/bin/perl

use IO::File;

#update: can also do that:
#noweave -filter "sed '/^@use /s/_/\\_/g;/^@defn /s/_/\\_/g'

my $file = $ARGV[0];

# automatic renaming of the xxx_yyy.zzz extension for noweb in <<>>= lines
# and more ...

open(OUTFILE, "> /tmp/yyy.nw");

sub process_file {
    my ($file) = @_;
    my $input = IO::File->new("< $file") or die "$! $file";

    my $inverbatim = 0;
    my $inchunk = 0;

    while(defined($line = $input->getline())) {
        if($line =~ /^#include \"(.*.tex.nw)\"/ ||
           $line =~ /^#include \"(.*.nw)\"/
          ) {
            process_file($1);
        } else {

            if($line =~ /begin{verbatim}/) { $inverbatim = 1; }
            if($line =~ /end{verbatim}/)   { $inverbatim = 0; }
            if($line =~ /^<<.*>>=/) { $inchunk = 1; }
            if($line =~ /^@/) { $inchunk = 0; }

            if($line =~ /<<.*>>/) {
                # must be before next case
                #TODO? $line =~ s/\[\[(.*?)\]\]/{\\tt $1}/g;
                $line =~ s/_/\\_/g;
            }

    #pad tricks for my comment macros
#    $line =~ s/^\\c (.*)$/\\footnote{\\verb+$1+}/;
    $line =~ s/^[ \t]*\\t (.*)$/\\SaveVerb{Verb}+$1+\\todo{\\UseVerb{Verb}}/;
    $line =~ s/^[ \t]*\\n (.*)$/\\SaveVerb{Verb}+$1+\\note{\\UseVerb{Verb}}/;
    $line =~ s/^[ \t]*\\l (.*)$/\\SaveVerb{Verb}+$1+\\less{\\UseVerb{Verb}}/;
    # can have code in comments that contains special symbol like <<
    # so simpler to just filter such code
    #update: but then in verbatim the line is skipped, which is annoying
    # for instance for lex %token declarations, so I commented it

            if($line =~ /^%/) {
                $line =~ s/^%.*/%/ if (!$inverbatim && !$inchunk);
             }
            if($inverbatim) {
                $line =~ s/<</xx/g;
            }
            print OUTFILE $line;
        }
    }
    $input->close();
}

process_file($file);

# use -delay ?
$filter="-filter ~/c__syncweb/scripts/dpp_ml.pl";
$filter="";
system("noweave $filter  -delay -index -latex /tmp/yyy.nw") 
    and die "'noweave' program is present ? $!";
