#!/usr/bin/perl

my $file = $ARGV[0];

`cp "$file" /tmp/xxx.nw`;

# automatic renaming of the xxx_yyy.zzz extension for noweb in <<>>= lines

open(INFILE, "< /tmp/xxx.nw");
open(OUTFILE, "> /tmp/yyy.nw");

while(<INFILE>) {
    my $line = $_;
    if($line =~ "<<.*>>") {
        $line =~ s/_/\\_/g;
    }
    print OUTFILE $line;
}
# use -delay ?
#$filter="-filter ~/c__syncweb/scripts/dpp_ml.pl";
$filter="-filter l2h";
system("noweave $filter  -index /tmp/yyy.nw");
