# Build syncweb via docker.
# See also Dockerfile at the root of the project.
# coupling: very similar to the docker.yml in codemap

name: docker

on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml:
          - 4.14.2
          #TODO: need to disable cmt if want to compile with 5.2.1
          # or use ifdefs in the code
          #- 5.2.1
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t "syncweb" --build-arg OCAML_VERSION=${{matrix.ocaml}} .
